services:
  - type: web
    name: portal-spotify-player
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
